#####################
#   ASIM SETTINGS   #
#####################

inherit_settings: True
scenario: 52_base_000

# input tables
input_table_list:
  - tablename: households
    filename: households.csv
    index_col: household_id
    column_map:
      household_id: household_id
      persons: hhsize
      workers: num_workers
      cars: VEHICL
  - tablename: persons
    filename: persons.csv
    index_col: person_id
    column_map:
      person_id: person_id
      member_id: PNUM
  - tablename: land_use
    filename: land_use.csv
    index_col: TAZ
    column_map:
      ZONE: TAZ
      COUNTY: county_id

# input skims
skims_file: skims.omx

# raise error if any sub-process fails without waiting for others to complete
fail_fast: True

strict: False

mem_tick: 0

use_shadow_pricing: False

# sample size
households_sample_size: 0

# multiprocessing controls
multiprocess: True
chunk_size: 15_000_000
num_processes: 70
stagger: 0

# tracing
trace_hh_id:
trace_od:

# to resume after last successful checkpoint, specify resume_after: _
# resume_after: _

models:
  ### mp_initialize step
  - initialize_landuse
  - compute_accessibility
  - initialize_households
  ### mp_households step
  - autonomous_vehicles
  - school_location
  - workplace_location
  - auto_ownership_simulate
  - free_parking
  - telework_job_sector
  - telework_option
  - telework
  - cdap_simulate
  - mandatory_tour_frequency
  - mandatory_tour_scheduling
  - joint_tour_frequency
  - joint_tour_composition
  - joint_tour_participation
  - joint_tour_destination
  - joint_tour_scheduling
  - non_mandatory_tour_frequency
  - non_mandatory_tour_destination
  - non_mandatory_tour_scheduling
  - tour_mode_choice_simulate
  - atwork_subtour_frequency
  - atwork_subtour_destination
  - atwork_subtour_scheduling
  - atwork_subtour_mode_choice
  - stop_frequency
  - trip_purpose
  - trip_destination
  - trip_purpose_and_destination
  - trip_scheduling
  - trip_mode_choice
  ### mp_summarize step
  - generate_beam_plans
  - write_data_dictionary
  - write_tables

multiprocess_steps:
  - name: mp_initialize
    begin: initialize_landuse
  - name: mp_households
    begin: autonomous_vehicles
    slice:
      tables:
        - households
        - persons
  - name: mp_summarize
    begin: generate_beam_plans

output_tables:
  action: include
  prefix: final_
  tables:
    - checkpoints
    - land_use
    - households
    - persons
    - tours
    - trips
    - joint_tour_participants
    - plans

# area_types less than this are considered urban
urban_threshold: 4
cbd_threshold: 2
rural_threshold: 6

skim_time_periods:
    period_minutes: 60
    periods:
        - 0
        - 6
        - 11
        - 16
        - 20
        - 24
    labels:
        - EA
        - AM
        - MD
        - PM
        - EV

# - value of time

# value_of_time = lognormal(np.log(median_value_of_time * mu), sigma).clip(min_vot, max_vot)

min_value_of_time: 1
max_value_of_time: 50
distributed_vot_mu: 0.684
distributed_vot_sigma: 0.85

household_median_value_of_time:
  1: 6.01
  2: 8.81
  3: 10.44
  4: 12.86
