COEFFS: tour_mode_choice_coeffs_v2.csv
CONSTANTS:
  bikeSpeed: 12.0
  bikeThresh: 6.0
  costPerMile: 14.632
  costShareSr2: 1.75
  costShareSr3: 2.5
  indivTour: 1.0
  longWalk: 0.667
  maxCbdAreaTypeThresh: 2
  shortWalk: 0.333
  upperAM: 10
  upperEA: 5
  upperMD: 15
  upperPM: 19
  waitThresh: 10.0
  walkSpeed: 3.5
  walkThresh: 2
LOGIT_TYPE: NL
LOGSUM_CHOOSER_COLUMNS:
- tour_type
- hhsize
- density_index
- age
- age_16_p
- age_16_to_19
- auto_ownership
- number_of_participants
- tour_category
- num_workers
- value_of_time
- free_parking_at_work
NESTS:
  alternatives:
  - alternatives:
    - alternatives:
      - DRIVEALONEFREE
      - DRIVEALONEPAY
      coefficient: 0.35
      name: DRIVEALONE
    - alternatives:
      - SHARED2FREE
      - SHARED2PAY
      coefficient: 0.35
      name: SHAREDRIDE2
    - alternatives:
      - SHARED3FREE
      - SHARED3PAY
      coefficient: 0.35
      name: SHAREDRIDE3
    coefficient: 0.71
    name: AUTO
  - alternatives:
    - WALK
    - BIKE
    coefficient: 0.9
    name: NONMOTORIZED
  - alternatives:
    - alternatives:
      - WALK_LOC
      - WALK_LRF
      - WALK_EXP
      - WALK_HVY
      - WALK_COM
      coefficient: 0.5
      name: WALKACCESS
    - alternatives:
      - DRIVE_LOC
      - DRIVE_LRF
      - DRIVE_EXP
      - DRIVE_HVY
      - DRIVE_COM
      coefficient: 0.5
      name: DRIVEACCESS
    coefficient: 0.5
    name: TRANSIT
  coefficient: 1.0
  name: root
SPEC: tour_mode_choice.csv
nontour_preprocessor:
  DF: choosers
  SPEC: tour_mode_choice_annotate_choosers_preprocessor
  TABLES:
  - land_use
preprocessor:
  DF: choosers
  SPEC: tour_mode_choice_annotate_choosers_preprocessor
  TABLES:
  - land_use
  - tours
